#ifndef AIRVAULT_ENGINE_H
#define AIRVAULT_ENGINE_H

/* Generated by cbindgen 0.29.4 from the Rust C ABI. Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

#define AV_INSTALL_PHASE_STAGING 0

#define AV_INSTALL_PHASE_INSTALLING 1

#define AV_ERROR_INVALID_ARGUMENT 1

#define AV_ERROR_DEVICE_UNAVAILABLE 2

#define AV_ERROR_DEVICE_LOCKED 3

#define AV_ERROR_TRUST_REQUIRED 4

#define AV_ERROR_USER_DENIED 5

#define AV_ERROR_BUSY 6

#define AV_ERROR_TIMEOUT 7

#define AV_ERROR_CANCELLED 8

#define AV_ERROR_PROTOCOL 9

#define AV_ERROR_STORAGE_FULL 10

#define AV_ERROR_INTEGRITY 11

#define AV_ERROR_UNSUPPORTED 12

#define AV_ERROR_INTERNAL 13

#define AV_ERROR_INVALID_BACKUP_PASSWORD 14

/**
 * The device may have accepted an irreversible mutation, but neither its
 * protocol verdict nor a post-condition probe can prove the final outcome.
 */
#define AV_ERROR_OUTCOME_UNKNOWN 15

/**
 * The phone refuses backup restores while Find My iPhone is on
 * (MBErrorDomain 211).
 */
#define AV_ERROR_FIND_MY_ENABLED 16

#define AV_STREAM_CONTINUE 100

#define AV_STREAM_CLOSED 101

/**
 * av_operation_cancel: no operation is registered under this id yet, so the
 * caller may retry until registration lands or the operation returns.
 */
#define AV_CANCEL_NOT_REGISTERED 3

typedef struct AvAfcFile AvAfcFile;

/**
 * Type-distinct FFI wrappers prevent a session from being passed to a file
 * operation (or vice versa). Both carry the connection's pool origin, so
 * closing either returns a healthy idle connection to the pool.
 */
typedef struct AvAfcSession AvAfcSession;

typedef struct AvConsoleStream AvConsoleStream;

/**
 * Immutable native-engine configuration owned by Go through an opaque pointer.
 */
typedef struct AvEngine AvEngine;

typedef struct AvLockStream AvLockStream;

typedef struct AvPresenceWatch AvPresenceWatch;

typedef struct {
  uint8_t *ptr;
  size_t len;
} AvBuffer;

typedef struct {
  AvBuffer detail;
} AvError;

/**
 * Install progress into Go. Percent is local to the reported phase.
 */
typedef void (*av_install_cb)(size_t, int32_t, uint64_t);

/**
 * Structured tracing event callback into the Go host. Strings are borrowed
 * for the duration of the call; `fields_json` is a flat JSON object.
 */
typedef void (*av_log_cb)(int32_t, const char*, const char*, const char*);

/**
 * Progress callback into Go: (opaque operation id, phase, percent, bytes).
 * Phase is BACKUP_PHASE_*; percent < 0 means "not reported this call", and
 * `bytes` is the session's cumulative total (0 = not reported this call).
 */
typedef void (*av_backup_cb)(size_t, int32_t, double, uint64_t);

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Reads the live activation state ("Unactivated", "Activated", ...).
 */
int32_t av_activation_state(AvEngine *engine,
                            const char *udid,
                            const char *job_id,
                            char **out_state,
                            AvError *error);

/**
 * Session blob for the drmHandshake POST, as an XML plist string.
 */
int32_t av_activation_session_info(AvEngine *engine,
                                   const char *udid,
                                   const char *job_id,
                                   char **out_xml,
                                   AvError *error);

/**
 * Builds the signed activation info from Apple's drmHandshake response.
 */
int32_t av_activation_info(AvEngine *engine,
                           const char *udid,
                           const char *job_id,
                           const uint8_t *handshake,
                           size_t handshake_len,
                           char **out_xml,
                           AvError *error);

/**
 * Applies Apple's activation record; `headers_json` carries the activation
 * response headers as a flat JSON object (may be empty).
 */
int32_t av_activation_finish(AvEngine *engine,
                             const char *udid,
                             const char *job_id,
                             const uint8_t *record,
                             size_t record_len,
                             const char *headers_json,
                             AvError *error);

/**
 * Opens an AFC session, reusing an idle pooled connection while it is healthy.
 * rc 0 or an AV_ERROR_* kind.
 */
int32_t av_afc_open(AvEngine *engine,
                    const uint8_t *udid_ptr,
                    size_t udid_len,
                    int32_t source,
                    const uint8_t *bundle_ptr,
                    size_t bundle_len,
                    AvAfcSession **out_session,
                    AvError *error);

/**
 * Lists raw child names using an existing AFC connection. rc 0 or an
 * AV_ERROR_* kind (cancelled = the session was closed/cancelled).
 */
int32_t av_afc_list(AvAfcSession *session,
                    const uint8_t *path_ptr,
                    size_t path_len,
                    char **out_json,
                    AvError *error);

/**
 * Reads raw metadata using an existing AFC connection. rc 0 or an AV_ERROR_* kind.
 */
int32_t av_afc_stat(AvAfcSession *session,
                    const uint8_t *path_ptr,
                    size_t path_len,
                    char **out_json,
                    AvError *error);

/**
 * Removes one path using an existing AFC connection. rc 0 or an AV_ERROR_* kind.
 */
int32_t av_afc_remove(AvAfcSession *session,
                      const uint8_t *path_ptr,
                      size_t path_len,
                      AvError *error);

/**
 * Reads one whole small file (bounded by buffer_len) on an existing session
 * WITHOUT consuming it — the bulk path for thumbnails. Large streaming stays on
 * file_open/file_read. rc 0 or an AV_ERROR_* kind.
 */
int32_t av_afc_read_small(AvAfcSession *session,
                          const uint8_t *path_ptr,
                          size_t path_len,
                          uint8_t *buffer,
                          size_t buffer_len,
                          size_t *out_read,
                          AvError *error);

/**
 * Transitions a session handle into one file for chunked reads, reporting its
 * size and modified time (unix seconds, 0 if unknown). rc 0 or an AV_ERROR_* kind.
 */
int32_t av_afc_file_open(AvAfcSession *session,
                         const uint8_t *path_ptr,
                         size_t path_len,
                         uint64_t *out_size,
                         int64_t *out_modified,
                         AvAfcFile **out_file,
                         AvError *error);

/**
 * Reads at most buffer_len bytes into the caller's buffer. rc 0 or an
 * AV_ERROR_* kind.
 */
int32_t av_afc_file_read(AvAfcFile *file,
                         uint8_t *buffer,
                         size_t buffer_len,
                         size_t *out_read,
                         AvError *error);

/**
 * Moves the read cursor to an absolute offset. rc 0 or an AV_ERROR_* kind.
 */
int32_t av_afc_file_seek(AvAfcFile *file, uint64_t offset, AvError *error);

/**
 * Interrupts an in-flight call without releasing the wrapper; the interrupted
 * connection is dropped, never pooled. Go calls this before waiting for the
 * in-flight FFI operation, then calls close after it returns.
 */
void av_afc_cancel(AvAfcSession *session);

void av_afc_file_cancel(AvAfcFile *file);

/**
 * Closes an AFC session and returns its idle connection to the pool. A null
 * pointer is a no-op.
 */
void av_afc_close(AvAfcSession *session);

/**
 * Closes an AFC file (one FileClose round trip) and returns its connection to
 * the pool. A null pointer is a no-op.
 */
void av_afc_file_close(AvAfcFile *file);

/**
 * Lists user-installed applications into out_json (see apps_inner). The
 * generous timeout covers devices with hundreds of apps — the lookup answer is big.
 */
int32_t av_apps_list(AvEngine *engine, const char *udid, char **out_json, AvError *error);

/**
 * Installs a user-provided .ipa (host path) onto the device. Blocking, hard-
 * capped — install can take a while. Returns diagnostic text on failure.
 */
int32_t av_app_install(AvEngine *engine,
                       const char *udid,
                       const char *job_id,
                       const char *ipa_path,
                       av_install_cb cb,
                       size_t callback_id,
                       AvError *error);

/**
 * Fetches one app icon into an owned binary buffer.
 */
int32_t av_app_icon(AvEngine *engine,
                    const char *udid,
                    const char *bundle_id,
                    AvBuffer *out,
                    AvError *error);

/**
 * Uninstalls an app by bundle id (installation_proxy).
 */
int32_t av_app_uninstall(AvEngine *engine,
                         const char *udid,
                         const char *job_id,
                         const char *bundle_id,
                         AvError *error);

/**
 * Opens a structured console stream; the session handle lands in out_stream.
 * Records flow immediately — pull them with av_console_next.
 */
int32_t av_console_open(AvEngine *engine,
                        const char *udid,
                        AvConsoleStream **out_stream,
                        AvError *error);

/**
 * Pulls the next log record as JSON via the AV_STREAM_* pull protocol:
 * 0 = record in out_json; any other rc is a stream error (session is dead).
 */
int32_t av_console_next(AvConsoleStream *stream, char **out_json, char **err);

void av_console_cancel(AvConsoleStream *stream);

/**
 * Releases a console session after its final `next` call has returned.
 */
void av_console_close(AvConsoleStream *stream);

/**
 * Sends a power command (0 = restart, 1 = shutdown, 2 = sleep) via the
 * diagnostics relay. Returns once the command is ACCEPTED — the device acts
 * asynchronously and (for restart/shutdown) drops off the muxer.
 */
int32_t av_device_power(AvEngine *engine,
                        const char *udid,
                        const char *job_id,
                        int32_t action,
                        AvError *error);

/**
 * Hardware/storage/battery-health snapshot as JSON (see device_info_inner).
 */
int32_t av_device_hardware(AvEngine *engine, const char *udid, char **out_json, AvError *error);

/**
 * Fetches a rendered wallpaper preview as raw PNG. `lock_screen` selects
 * lock (non-zero) or home (zero).
 */
int32_t av_wallpaper_get(AvEngine *engine,
                         const char *udid,
                         int32_t lock_screen,
                         AvBuffer *out,
                         AvError *error);

/**
 * Discovers reachable devices WITH lockdown metadata (see DiscoverItem).
 * No connection field on purpose — presence/transport is the watcher's domain.
 */
int32_t av_devices_inspect(AvEngine *engine, char **out_json, AvError *error);

/**
 * Cheap availability check (NO lockdown metadata): [{"udid","connection"}]
 * into out_json. A one-shot pull for startup/reconcile; live presence
 * normally comes from the owned presence watcher.
 */
int32_t av_devices_list(AvEngine *engine, char **out_json, AvError *error);

/**
 * Reads battery into `out_json`: {"charging":bool,"level":int}. Bounded — a
 * Wi-Fi lockdown session can hang.
 */
int32_t av_device_battery(AvEngine *engine, const char *udid, char **out_json, AvError *error);

/**
 * Lists USB devices into out_json (for the pairing wizard).
 */
int32_t av_usb_devices_list(AvEngine *engine, char **out_json, AvError *error);

/**
 * Free any string handed out by this shim (including error text).
 *
 * # Safety
 * `s` must be a string returned by this shim, or null.
 */
void av_string_free(char *s);

void av_buffer_free(AvBuffer buffer);

/**
 * Creates an engine with immutable provider and storage configuration.
 */
AvEngine *av_engine_new(const char *backup_root,
                        const char *pairing_root,
                        const char *mux_address,
                        char **err);

/**
 * Releases an engine after every operation and stream has joined.
 */
void av_engine_free(AvEngine *engine);

/**
 * Cancels the exact in-flight transfer or bounded device command. 0 = delivered,
 * AV_CANCEL_NOT_REGISTERED = operation is not running, other = bad input.
 */
int32_t av_operation_cancel(AvEngine *engine, const char *operation_id);

/**
 * Reports whether the muxer (usbmuxd/netmuxd) is reachable. The ABI's one
 * predicate-style return: 1 = up, 0 = down (a hung socket counts as down).
 */
int32_t av_mux_probe(AvEngine *engine);

int32_t av_lock_observer_open(AvEngine *engine,
                              const char *udid,
                              AvLockStream **out,
                              AvError *error);

int32_t av_lock_observer_next(AvLockStream *stream, int32_t *out_event, char **err);

void av_lock_observer_close(AvLockStream *stream);

void av_lock_observer_cancel(AvLockStream *stream);

/**
 * Connects Rust tracing to the host logger before the runtime starts. The
 * selected application level applies to this crate; dependency warnings stay
 * available without enabling their high-volume info/debug streams.
 *
 * # Safety
 * `level` must be null or point to a valid NUL-terminated string for the call.
 */
int32_t av_log_init(av_log_cb cb, const char *level);

/**
 * Unpairs: lockdown `Unpair` so the phone forgets this host, then our host
 * record goes — independently, whatever the phone answered, so no device can
 * become unremovable. AV_ERROR_INTERNAL = that removal itself failed.
 */
int32_t av_pairing_unpair(AvEngine *engine, const char *udid, AvError *error);

/**
 * Triggers/advances pairing. out_status: "paired" | "trust_pending" |
 * "denied" | "locked" | "wifi_authorization_failed".
 */
int32_t av_pairing_advance(AvEngine *engine,
                           const char *udid,
                           const char *job_id,
                           char **out_status,
                           AvError *error);

/**
 * Backup-password management: empty old_pw enables encryption, empty new_pw
 * disables it, both set change it; the long bound covers the device-passcode
 * wait. out_encrypted (-1 = unknown, else the device flag) is set even on error.
 */
int32_t av_backup_password_change(AvEngine *engine,
                                  const char *udid,
                                  const char *job_id,
                                  const char *old_pw,
                                  const char *new_pw,
                                  int32_t *out_encrypted,
                                  AvError *error);

/**
 * Runs a backup into a staging whole-file object manifest. An empty base ID
 * starts the first full snapshot. On rc 0, `added_bytes` (if non-null)
 * receives the payload bytes this backup added to the object pool.
 */
int32_t av_snapshot_build(AvEngine *engine,
                          const char *udid,
                          const char *job_id,
                          const char *snapshot_id,
                          const char *base_snapshot_id,
                          av_backup_cb cb,
                          size_t callback_id,
                          uint64_t *added_bytes,
                          AvError *error);

/**
 * Restores one immutable whole-file object snapshot.
 */
int32_t av_snapshot_restore(AvEngine *engine,
                            const char *udid,
                            const char *job_id,
                            const char *source,
                            const char *snapshot_id,
                            const char *password,
                            int32_t system_files,
                            int32_t reboot,
                            int32_t settings_from_backup,
                            int32_t remove_items_not_restored,
                            av_backup_cb cb,
                            size_t callback_id,
                            AvError *error);

/**
 * Opens one independently-owned presence watcher.
 */
int32_t av_device_watch_open(AvEngine *engine, AvPresenceWatch **out, AvError *error);

/**
 * Pulls the next complete state JSON via the AV_STREAM_* pull protocol.
 */
int32_t av_device_watch_next(AvPresenceWatch *watcher, char **out_json, char **err);

/**
 * Signals cancellation without releasing the watcher.
 */
void av_device_watch_cancel(AvPresenceWatch *watcher);

/**
 * Joins and releases a watcher after its final `next` call has returned.
 */
void av_device_watch_close(AvPresenceWatch *watcher);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* AIRVAULT_ENGINE_H */
