// One barrel import: Vite tree-shakes it down to these icons.
import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  BatteryCharging,
  BatteryFull,
  BatteryLow,
  BatteryMedium,
  Battery,
  BookUser,
  Check,
  ChevronLeft,
  ChevronRight,
  Clock,
  Cloud,
  CornerLeftUp,
  DatabaseArrowDown,
  DatabaseBackup,
  Download,
  EllipsisVertical,
  Eye,
  EyeOff,
  File,
  Folder,
  FolderOpen,
  Image,
  Info,
  KeyRound,
  LayoutGrid,
  Lock,
  LockOpen,
  LogOut,
  MessageCircle,
  MessagesSquare,
  NotebookPen,
  Moon,
  Pause,
  Phone,
  PhoneIncoming,
  PhoneMissed,
  PhoneOutgoing,
  Play,
  Power,
  RefreshCw,
  ShieldCheck,
  Smartphone,
  Sun,
  Tablet,
  Terminal,
  Trash,
  TriangleAlert,
  Unplug,
  Upload,
  Usb,
  Wifi,
  X,
} from '@lucide/svelte';

export const ICONS = {
  wifi: Wifi,
  usb: Usb,
  offline: Unplug,
  phone: Smartphone,
  tablet: Tablet,
  lock: Lock,
  unlocked: LockOpen,
  key: KeyRound,
  logout: LogOut,
  shield: ShieldCheck,
  check: Check,
  x: X,
  refresh: RefreshCw,
  clock: Clock,
  cloud: Cloud,
  folder: Folder,
  file: File,
  image: Image,
  levelUp: CornerLeftUp,
  download: Download,
  battery: Battery,
  batteryLow: BatteryLow,
  batteryMedium: BatteryMedium,
  batteryFull: BatteryFull,
  batteryCharging: BatteryCharging,
  more: EllipsisVertical,
  moon: Moon,
  sun: Sun,
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  backup: DatabaseArrowDown,
  restore: DatabaseBackup,
  browse: FolderOpen,
  contacts: BookUser,
  call: Phone,
  callIncoming: PhoneIncoming,
  callMissed: PhoneMissed,
  callOutgoing: PhoneOutgoing,
  messages: MessagesSquare,
  chat: MessageCircle,
  notes: NotebookPen,
  alert: TriangleAlert,
  info: Info,
  plug: Usb, // pairing is over USB
  terminal: Terminal,
  power: Power,
  apps: LayoutGrid,
  pause: Pause,
  play: Play,
  upload: Upload,
  eye: Eye,
  eyeOff: EyeOff,
} as const;

export type IconName = keyof typeof ICONS;
