// One barrel import: Vite tree-shakes it down to these icons.
import {
  ArrowLeft,
  ArrowRight,
  BatteryCharging,
  BatteryFull,
  BatteryLow,
  BatteryMedium,
  Battery,
  Check,
  ChevronLeft,
  ChevronRight,
  Clock,
  CornerLeftUp,
  DatabaseBackup,
  Download,
  EllipsisVertical,
  File,
  Folder,
  Image,
  Info,
  LayoutGrid,
  Lock,
  LockOpen,
  LogOut,
  Moon,
  Pause,
  Play,
  Power,
  RefreshCw,
  ShieldCheck,
  Smartphone,
  Sun,
  Tablet,
  Terminal,
  Trash,
  TriangleAlert,
  Unplug,
  Upload,
  Usb,
  Wifi,
  X,
} from '@lucide/svelte';

export const ICONS = {
  wifi: Wifi,
  usb: Usb,
  offline: Unplug,
  phone: Smartphone,
  tablet: Tablet,
  lock: Lock,
  unlocked: LockOpen,
  logout: LogOut,
  shield: ShieldCheck,
  check: Check,
  x: X,
  refresh: RefreshCw,
  clock: Clock,
  folder: Folder,
  file: File,
  image: Image,
  levelUp: CornerLeftUp,
  download: Download,
  battery: Battery,
  batteryLow: BatteryLow,
  batteryMedium: BatteryMedium,
  batteryFull: BatteryFull,
  batteryCharging: BatteryCharging,
  more: EllipsisVertical,
  moon: Moon,
  sun: Sun,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  backup: DatabaseBackup,
  alert: TriangleAlert,
  info: Info,
  plug: Usb, // pairing is over USB
  terminal: Terminal,
  power: Power,
  apps: LayoutGrid,
  pause: Pause,
  play: Play,
  upload: Upload,
} as const;

export type IconName = keyof typeof ICONS;
